# Generated by Django 6.0.4 on 2026-04-21 02:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0006_alter_shop_base_currency_alter_shopmember_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('META', 'Meta'), ('BKASH', 'bKash'), ('COURIER', 'Courier')], max_length=20)),
                ('event_type', models.CharField(blank=True, max_length=120)),
                ('external_event_id', models.CharField(max_length=255)),
                ('dedupe_hash', models.CharField(blank=True, max_length=255)),
                ('payload_fingerprint', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('PROCESSED', 'Processed'), ('DUPLICATE', 'Duplicate'), ('FAILED', 'Failed'), ('REJECTED', 'Rejected')], default='PROCESSED', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_logs', to='shops.shop')),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'external_event_id'], name='webhook_provider_event_idx'), models.Index(fields=['shop', 'created_at'], name='webhook_shop_created_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'external_event_id'), name='uq_webhook_provider_external_id')],
            },
        ),
    ]
