# Generated by Django 6.0.4 on 2026-04-24 13:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0010_shop_custom_domain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantAPIToken',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant that owns this record')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('token_prefix', models.CharField(max_length=12)),
                ('scopes', models.JSONField(default=list)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_api_tokens', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to='shops.shop')),
            ],
            options={
                'indexes': [models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['shop'], name='billing_apitoken_shop_idx')],
            },
        ),
        migrations.CreateModel(
            name='OutboundWebhook',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant that owns this record')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(help_text='HTTPS endpoint that receives events.', max_length=500)),
                ('secret', models.CharField(help_text='HMAC-SHA256 signing secret. Shown once on creation.', max_length=64)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('FAILED', 'Disabled (Repeated Failures)')], default='ACTIVE', max_length=10)),
                ('subscribed_events', models.JSONField(default=list)),
                ('consecutive_failures', models.PositiveSmallIntegerField(default=0)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_webhooks', to='shops.shop')),
            ],
            options={
                'indexes': [models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['shop', 'status'], name='billing_wh_shop_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='PaymentGatewayConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant that owns this record')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gateway', models.CharField(choices=[('BKASH', 'bKash (Tokenized)'), ('SSLCOMMERZ', 'SSLCommerz'), ('PORTPOS', 'PortPOS'), ('MANUAL', 'Manual / Bank Transfer')], max_length=20)),
                ('credentials_encrypted', models.TextField(blank=True, help_text='JSON-encoded gateway credentials stored encrypted. Use billing.services.gateway.set_gateway_credentials() to write — never write directly.')),
                ('label', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Merchant can disable a gateway without deleting its credentials.')),
                ('is_test_mode', models.BooleanField(default=False, help_text='Toggles the gateway SDK to its sandbox environment.')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_gateways', to='shops.shop')),
            ],
            options={
                'indexes': [models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['shop', 'is_active'], name='billing_gw_shop_active_idx')],
                'unique_together': {('shop', 'gateway')},
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant that owns this record')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('COD', 'Cash on Delivery'), ('BKASH', 'bKash'), ('SSLCOMMERZ', 'SSLCommerz / Card'), ('PORTPOS', 'PortPOS'), ('BANK_TRANSFER', 'Bank Transfer'), ('CUSTOM', 'Custom Manual Payment')], max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('fee_payer', models.CharField(choices=[('MERCHANT', 'Merchant absorbs fee'), ('CUSTOMER', 'Customer pays fee')], default='MERCHANT', help_text='Defaults to merchant per global_business_rules_and_limits.md §3.', max_length=10)),
                ('custom_instructions', models.TextField(blank=True, help_text="e.g. 'Send to bKash 01XXXXXXXXX and paste your TxnID below.'")),
                ('requires_transaction_id', models.BooleanField(default=False)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='shops.shop')),
            ],
            options={
                'ordering': ['display_order'],
                'indexes': [models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['shop', 'is_enabled'], name='billing_pm_shop_enabled_idx')],
                'unique_together': {('shop', 'method')},
            },
        ),
        migrations.CreateModel(
            name='ShopSubscription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant that owns this record')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tier', models.CharField(choices=[('FREE', 'Free'), ('BASIC', 'Basic — 990 ৳/mo'), ('PRO', 'Pro — 1,990 ৳/mo'), ('BUSINESS', 'Business — 4,990 ৳/mo'), ('CUSTOM', 'Custom / Staff Plan')], default='FREE', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('GRACE', 'Grace Period'), ('SUSPENDED', 'Suspended'), ('COMPLIANCE_LOCK', 'Compliance Lock'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('grace_period_until', models.DateTimeField(blank=True, help_text='If set, shop is in grace period until this datetime. After this, status → SUSPENDED.', null=True)),
                ('last_paid_at', models.DateTimeField(blank=True, null=True)),
                ('is_billing_exempt', models.BooleanField(default=False, help_text='Admin-only. Completely skips billing enforcement for test/staff shops.')),
                ('admin_note', models.TextField(blank=True)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='shops.shop')),
            ],
            options={
                'indexes': [models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['shop'], name='billing_sub_shop_active_idx'), models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['status'], name='billing_sub_status_active_idx')],
            },
        ),
    ]
