# Generated by Django 6.0.4 on 2026-04-26 15:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_outboundwebhook_deleted_at_bkashagreement_and_more'),
        ('shops', '0011_merge_0008_prepaid_and_0010_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='AICreditPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('credits', models.PositiveIntegerField()),
                ('retail_price_bdt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'credits'],
            },
        ),
        migrations.CreateModel(
            name='AICreditTopUp',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant that owns this record')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credits_purchased', models.PositiveIntegerField()),
                ('amount_paid_bdt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.aicreditpackage')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_topups', to='shops.shop')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_topup_record', to='billing.paymenttransaction')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
