# Generated by Django 6.0.4 on 2026-04-26 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_enable_pgvector'),
        ('shops', '0011_merge_0008_prepaid_and_0010_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant that owns this record')),
                ('usage_type', models.CharField(choices=[('CHAT_COMPLETION', 'Chat Completion'), ('EMBEDDING', 'Embedding'), ('IMAGE_GENERATION', 'Image Generation')], db_index=True, max_length=32)),
                ('provider', models.CharField(choices=[('OPENAI', 'OpenAI'), ('ANTHROPIC', 'Anthropic'), ('STABILITY', 'Stability AI'), ('CUSTOM', 'Custom')], max_length=20)),
                ('model_name', models.CharField(max_length=100)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('usd_cost', models.DecimalField(decimal_places=8, default=0, max_digits=14)),
                ('credits_deducted', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('reference_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='aimodelregistry',
            name='uq_ai_model_single_default_per_usage',
        ),
        migrations.AddConstraint(
            model_name='aimodelregistry',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_default', True)), fields=('usage',), name='uq_ai_model_single_default_per_usage'),
        ),
        migrations.AddField(
            model_name='aiusagelog',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_logs', to='shops.shop'),
        ),
        migrations.AddIndex(
            model_name='aiusagelog',
            index=models.Index(fields=['shop', 'created_at'], name='ai_usage_shop_created_idx'),
        ),
    ]
