# Generated by Django 6.0.4 on 2026-04-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_establish_materialized_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='CohortData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField()),
                ('cohort_month', models.DateField()),
                ('signup_count', models.IntegerField()),
            ],
            options={
                'db_table': 'analytics_cohort_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerLTV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField()),
                ('total_orders', models.IntegerField()),
                ('lifetime_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('last_purchase_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'analytics_customer_ltv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShopSalesMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField()),
                ('date', models.DateField()),
                ('total_orders', models.IntegerField()),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('avg_order_value', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'analytics_shop_sales_metrics',
                'managed': False,
            },
        ),
    ]
