# Generated by Django 6.0.4 on 2026-04-26 14:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0011_merge_0008_prepaid_and_0010_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('reward_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reward_applied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referred_shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_info', to='shops.shop')),
                ('referrer_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_sent', to='shops.shop')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AffiliateClick',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('referer_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referrer_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_clicks', to='shops.shop')),
            ],
            options={
                'indexes': [models.Index(fields=['referrer_shop', 'created_at'], name='affiliates__referre_623f92_idx')],
            },
        ),
    ]
