# Generated by Django 6.0.4 on 2026-04-26 15:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
        ('shops', '0011_merge_0008_prepaid_and_0010_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaAdAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant that owns this record')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('currency', models.CharField(default='BDT', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_accounts', to='shops.shop')),
            ],
        ),
        migrations.CreateModel(
            name='MetaAdCampaign',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant that owns this record')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_campaign_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('daily_budget_bdt', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('targeting_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ad_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='marketing.metaadaccount')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_campaigns', to='shops.shop')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MetaUserAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant that owns this record')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meta_user_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('access_token', models.TextField()),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta_user_account', to='shops.shop')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='metaadaccount',
            index=models.Index(fields=['shop', 'is_active'], name='marketing_m_shop_id_2e6bbf_idx'),
        ),
    ]
