# Generated by Django 6.0.4 on 2026-04-26 14:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0011_merge_0008_prepaid_and_0010_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant that owns this record')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('opt_in_pooling', models.BooleanField(default=True, help_text='Contribute to and benefit from the global fraud pool.')),
                ('block_high_risk', models.BooleanField(default=False, help_text='Automatically block orders from high-risk numbers.')),
                ('warn_on_rto', models.BooleanField(default=True, help_text='Show warning in dashboard for customers with RTO history.')),
                ('rto_threshold', models.PositiveIntegerField(default=2, help_text='Number of RTOs before a customer is flagged as high-risk.')),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_config', to='shops.shop')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FraudReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant that owns this record')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=20)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('phone_hash', models.CharField(db_index=True, max_length=64)),
                ('reason', models.CharField(choices=[('RTO', 'Return To Origin (RTO)'), ('FAKE_ORDER', 'Fake Order / Prank'), ('HARASSMENT', 'Harassment'), ('UNPAID', 'Unpaid Advanced Fee')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_reports', to='shops.shop')),
            ],
            options={
                'indexes': [models.Index(fields=['phone_hash'], name='fraud_phone_hash_idx'), models.Index(fields=['shop', 'reported_at'], name='fraud_shop_report_idx')],
            },
        ),
    ]
