# Generated by Django 6.0.4 on 2026-04-26 14:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalFraudPool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('rto_count', models.PositiveIntegerField(default=0)),
                ('fake_order_count', models.PositiveIntegerField(default=0)),
                ('harassment_count', models.PositiveIntegerField(default=0)),
                ('unpaid_count', models.PositiveIntegerField(default=0)),
                ('last_reported_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
