# Generated by Django 5.0.14 on 2026-04-18 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql='''
                ALTER TABLE shops_customerprofile ENABLE ROW LEVEL SECURITY;
                CREATE POLICY tenant_isolation_policy ON shops_customerprofile 
                USING (tenant_id::text = current_setting('app.current_shop_id', TRUE));
            ''',
            reverse_sql='''
                DROP POLICY tenant_isolation_policy ON shops_customerprofile;
                ALTER TABLE shops_customerprofile DISABLE ROW LEVEL SECURITY;
            '''
        )
    ]
