# Generated by Django 6.0.4 on 2026-04-18 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_rls_policies'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('FREE', 'Free'), ('BASIC', 'Basic'), ('PRO', 'Pro'), ('BUSINESS', 'Business')], max_length=20, unique=True)),
                ('max_products', models.IntegerField(default=5)),
                ('max_staff', models.IntegerField(default=1)),
                ('can_use_pos', models.BooleanField(default=False)),
                ('can_use_api', models.BooleanField(default=False)),
                ('can_use_pixels', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='shop',
            name='override_max_staff',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='packaging_weight_grams',
            field=models.PositiveIntegerField(default=0, help_text="Added to every order's total weight for accurate courier billing"),
        ),
        migrations.AddField(
            model_name='shop',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shops', to='shops.subscriptionplan'),
        ),
    ]
