# Generated by Django 6.0.4 on 2026-04-21 02:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_shop_base_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopmember',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('INVENTORY_MANAGER', 'Inventory Manager'), ('CASHIER', 'Cashier')], default='CASHIER', max_length=20),
        ),
        migrations.CreateModel(
            name='ShopSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant that owns this record')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stock_reservation_minutes', models.PositiveIntegerField(default=30)),
                ('allow_guest_checkout', models.BooleanField(default=True)),
                ('mandatory_advance_fee_bdt', models.PositiveIntegerField(default=0)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('branding_slug_release_days', models.PositiveIntegerField(default=30)),
                ('ai_credit_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('sms_balance_credits', models.PositiveIntegerField(default=0)),
                ('notification_targets', models.JSONField(blank=True, default=list)),
                ('messenger_context_window_size', models.PositiveIntegerField(default=20)),
                ('messenger_human_takeover_ttl_minutes', models.PositiveIntegerField(default=30)),
                ('messenger_max_orders_per_psid_per_day', models.PositiveIntegerField(default=5)),
                ('messenger_order_draft_ttl_hours', models.PositiveIntegerField(default=24)),
                ('messenger_fallback_message', models.TextField(default="I'm having a little trouble right now. Our team will reach out to you shortly! 🙏")),
                ('custom_domain_verified', models.BooleanField(default=False)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='shops.shop')),
            ],
            options={
                'indexes': [models.Index(fields=['shop', 'deleted_at'], name='shopsettings_shop_deleted_idx')],
            },
        ),
    ]
