# Generated by Django 6.0.4 on 2026-04-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_alter_shop_base_currency_alter_shopmember_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsettings',
            name='messenger_greeting_keywords',
            field=models.JSONField(blank=True, default=list, help_text='Case-insensitive full-message greeting keywords that trigger an auto-welcome without using AI credits. Leave empty to use the system defaults.'),
        ),
    ]
