# Generated by Django 6.0.4 on 2026-04-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_v0_6_messenger_faq_greeting_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsettings',
            name='discount_application',
            field=models.CharField(choices=[('EXCLUSIVE', 'Discount is Exclusive of Tax'), ('INCLUSIVE', 'Discount is Inclusive of Tax')], default='EXCLUSIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='enable_product_reviews',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='show_stock_count',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='tax_calculation_base',
            field=models.CharField(choices=[('ORIGINAL', 'Calculate Tax on Original Price'), ('DISCOUNTED', 'Calculate Tax on Discounted Price')], default='DISCOUNTED', max_length=20),
        ),
    ]
