# Generated by Django 6.0.4 on 2026-04-24 10:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0008_shopsettings_discount_application_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreTheme',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant that owns this record')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('theme_id', models.CharField(choices=[('minimalist', 'Minimalist'), ('bold', 'Bold & Tech'), ('elegance', 'Soft Elegance'), ('urban', 'Urban Streetwear')], default='minimalist', max_length=50)),
                ('aesthetic_overrides', models.JSONField(blank=True, default=dict)),
                ('active_components', models.JSONField(blank=True, default=dict)),
                ('typography', models.JSONField(blank=True, default=dict)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme', to='shops.shop')),
            ],
            options={
                'indexes': [models.Index(fields=['shop', 'deleted_at'], name='storetheme_shop_deleted_idx')],
            },
        ),
    ]
