# Generated by Django 6.0.4 on 2026-04-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0009_storetheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='custom_domain',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
    ]
