# Generated by Django 6.0.4 on 2026-04-18 15:07

import django.contrib.postgres.search
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nishchinto_media', '0001_initial'),
        ('shops', '0004_subscriptionplan_shop_override_max_staff_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant that owns this record')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.category')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='shops.shop')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant that owns this record')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('slug', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('SCHEDULED', 'Scheduled'), ('OUT_OF_STOCK', 'Out of Stock'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=15)),
                ('publish_at', models.DateTimeField(blank=True, null=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=0, help_text='e.g. 0.1500 = 15%', max_digits=5)),
                ('sku', models.CharField(blank=True, max_length=120)),
                ('weight_grams', models.PositiveIntegerField(blank=True, help_text='Master weight in grams', null=True)),
                ('length_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('width_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_digital', models.BooleanField(default=False)),
                ('specifications', models.JSONField(blank=True, default=dict)),
                ('seo_title', models.CharField(blank=True, max_length=120)),
                ('seo_description', models.TextField(blank=True, max_length=320)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category')),
                ('shop', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shops.shop')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant that owns this record')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_thumbnail', models.BooleanField(default=False, help_text="If True, this image is used as the product's primary thumbnail")),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_links', to='nishchinto_media.media')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_media', to='catalog.product')),
                ('shop', models.ForeignKey(db_index=False, help_text='Denormalized for RLS efficiency', on_delete=django.db.models.deletion.CASCADE, related_name='product_media_links', to='shops.shop')),
            ],
            options={
                'verbose_name': 'Product Media',
                'verbose_name_plural': 'Product Media',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant that owns this record')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attribute_name_1', models.CharField(blank=True, max_length=50)),
                ('attribute_value_1', models.CharField(blank=True, max_length=100)),
                ('attribute_name_2', models.CharField(blank=True, max_length=50)),
                ('attribute_value_2', models.CharField(blank=True, max_length=100)),
                ('sku', models.CharField(blank=True, max_length=120)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, help_text='Overrides master product price if set', max_digits=10, null=True)),
                ('weight_override_grams', models.PositiveIntegerField(blank=True, help_text='Overrides master product weight if set', null=True)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variant_images', to='nishchinto_media.media')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product')),
                ('shop', models.ForeignKey(db_index=False, help_text='Denormalized for RLS index efficiency', on_delete=django.db.models.deletion.CASCADE, related_name='product_variants', to='shops.shop')),
            ],
            options={
                'verbose_name': 'Product Variant',
                'verbose_name_plural': 'Product Variants',
            },
        ),
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField(help_text='Positive = restock, negative = deduction')),
                ('reason', models.CharField(choices=[('SALE', 'Sale'), ('RESTOCK', 'Restock'), ('ADJUSTMENT', 'Manual Adjustment'), ('RETURN', 'Return'), ('IMPORT', 'Import')], max_length=15)),
                ('reference_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_actions', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_logs', to='shops.shop')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_logs', to='catalog.productvariant')),
            ],
            options={
                'verbose_name': 'Inventory Log',
                'verbose_name_plural': 'Inventory Logs',
            },
        ),
        migrations.CreateModel(
            name='ShopTrackingConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fb_pixel_id', models.CharField(blank=True, max_length=50)),
                ('ga4_measurement_id', models.CharField(blank=True, help_text='Format: G-XXXXXXXXXX', max_length=50)),
                ('gtm_id', models.CharField(blank=True, help_text='Format: GTM-XXXXXXX', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_config', to='shops.shop')),
            ],
            options={
                'verbose_name': 'Shop Tracking Config',
                'verbose_name_plural': 'Shop Tracking Configs',
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['shop', 'parent'], name='category_shop_parent_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['shop', 'sort_order'], name='category_shop_sort_idx'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('shop', 'slug'), name='uq_category_shop_slug_active'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['shop', 'status'], name='product_shop_status_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['shop', 'sort_order'], name='product_shop_sort_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True), ('status', 'SCHEDULED')), fields=['status', 'publish_at'], name='product_scheduled_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['search_vector'], name='product_search_vector_gin_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('shop', 'slug'), name='uq_product_shop_slug_active'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('sku__gt', '')), fields=('shop', 'sku'), name='uq_product_shop_sku_active'),
        ),
        migrations.AddIndex(
            model_name='productmedia',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['product', 'sort_order'], name='productmedia_product_sort_idx'),
        ),
        migrations.AddConstraint(
            model_name='productmedia',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_thumbnail', True)), fields=('product',), name='uq_productmedia_one_thumbnail'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['shop', 'product'], name='variant_shop_product_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True), ('sku__gt', '')), fields=['shop', 'sku'], name='variant_shop_sku_idx'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('sku__gt', '')), fields=('shop', 'sku'), name='uq_variant_shop_sku_active'),
        ),
        migrations.AddIndex(
            model_name='inventorylog',
            index=models.Index(fields=['shop', 'variant', 'created_at'], name='invlog_shop_var_created_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorylog',
            index=models.Index(fields=['shop', 'created_at'], name='invlog_shop_created_idx'),
        ),
    ]
