# Generated by Django 6.0.4 on 2026-04-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Default COGS for profit calculation', max_digits=10),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='purchase_price_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Overrides master purchase_price if set', max_digits=10, null=True),
        ),
    ]
