# Generated by Django 6.0.4 on 2026-04-24 06:20

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0007_v0_6_messenger_faq_greeting_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant that owns this record')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('FAQ', 'FAQ'), ('RETURN_POLICY', 'Return Policy'), ('SHIPPING_POLICY', 'Shipping Policy'), ('TERMS_OF_SERVICE', 'Terms of Service'), ('CUSTOM', 'Custom')], db_index=True, default='FAQ', max_length=20)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_entries', to='shops.shop')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
                'indexes': [models.Index(fields=['shop', 'is_active', 'sort_order'], name='faq_shop_active_order_idx')],
            },
        ),
        migrations.CreateModel(
            name='MessengerMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant that owns this record')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('psid', models.CharField(db_index=True, max_length=255)),
                ('page_id', models.CharField(db_index=True, max_length=255)),
                ('direction', models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound')], default='INBOUND', max_length=8)),
                ('message_text', models.TextField(blank=True, null=True)),
                ('attachment_payload', models.JSONField(blank=True, null=True)),
                ('mid', models.CharField(max_length=255, unique=True)),
                ('timestamp', models.BigIntegerField(db_index=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messenger_messages', to='shops.shop')),
            ],
            options={
                'indexes': [models.Index(fields=['shop', 'psid', 'timestamp'], name='msg_shop_psid_ts_idx'), models.Index(fields=['created_at'], name='msg_created_at_idx')],
            },
        ),
    ]
