# Generated by Django 6.0.4 on 2026-04-18 15:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0004_subscriptionplan_shop_override_max_staff_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=512)),
                ('s3_key', models.CharField(db_index=True, max_length=1024, unique=True)),
                ('cdn_url', models.URLField(blank=True, max_length=2048)),
                ('md5_hash', models.CharField(blank=True, db_index=True, max_length=32)),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=127)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('processing_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('DONE', 'Done'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('shop', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to='shops.shop')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Media',
                'indexes': [models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['shop', 'created_at'], name='media_shop_created_idx'), models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['s3_key'], name='media_s3key_active_idx')],
            },
        ),
    ]
