# Generated by Django 6.0.4 on 2026-04-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='cleared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='is_cleared',
            field=models.BooleanField(default=False, help_text='True if pending funds moved to current balance'),
        ),
    ]
